#!/bin/bash

mirror="http://l4u-00.jinr.ru/LinuxArchive/Ftp/tinycorelinux/"
dist_dir="4.x/x86/release/distribution_files/"
tcz_dir="4.x/x86/tcz/"

function _download() {
    for file in $*; do
        if [ -f ${file} ]; then
            echo -n "File '$file' exists, overwrite (y/n)? "
            read resp
            if [ $resp == "y" ]; then
                rm -f $file
                wget ${mirror}${dist_dir}${file}
            fi
        else 
            wget ${mirror}${dist_dir}${file}
        fi
    done
}

function _download_packages() {
    pushd tce/optional
    for file in $*; do
        if ! [ -f ${file}.tcz ]; then
            sudo wget ${mirror}${tcz_dir}${file}.tcz
        else
            echo "-> hit: ${file}.tcz"
        fi
        if ! [ -f ${file}.tcz.dep ]; then
            sudo wget ${mirror}${tcz_dir}${file}.tcz.dep
        else
            echo "-> hit: ${file}.tcz.dep"
        fi
    done
    popd
}

function _silent() {
    $* &> /dev/null;
}

function _purge() {
    pushd ${tce}/optional
    for file in $*; do
        sudo rm -f ${file}.tcz{,.dep}
    done
    popd
}

function _onboot() {
    for file in $*; do
        echo $file | sudo sh -c "cat >> tce/onboot.lst"
    done
}

function _image_mount() {
    imgfile=$1
    if ! [ -f $imgfile ]; then
        echo "error: image '"$imgfile"' doesn't exist"
        exit 1
    fi
    mkdir __image__
    sync
    sudo mount -o loop ${imgfile} __image__
    pushd __image__
}

function _image_umount() {
    popd
    sync
    sudo umount __image__
    rmdir __image__
    sync    
}

function _image_check_mounted() {
    currdir=$(basename $(pwd))
    if ! [ currdir != "__image__" ]; then
        echo "error: image not mounted"
        exit 1
    fi
}

function _image_init() {
    _image_check_mounted
    sudo mkdir -p tce/{optional,ondemand}
    sudo touch tce/onboot.lst
    sudo touch tce/bootlocal.sh # this is called from /opt/bootlocal.sh
    _download_packages mirrors kmaps
    _onboot mirrors.tcz kmaps.tcz
}

function _image_convert() {
    imgname=$1
    if ! [ -f $imgname ]; then
        echo "error: image '"$imgname"' doesn't exist"
        exit 1
    fi
    qemu-img convert -O qcow2 ${imgname} __tmp.img
    mv __tmp.img ${imgname}
}

# init 
function download() {
    # Download 'core.gz' and 'vmlinuz' from TinyCoreLinux
    _download core.gz vmlinuz
}

function unpack() {
    file=$1
    dir=$2
    if [ -z $dir ]; then
        echo "error: no dir specified"
        exit 1
    fi

    if ! [ -f $file ]; then
        echo "'"$file"' does no exist"
    fi
    
    if [ -d $dir ]; then
        echo -n "Erase existing dir (y/n): "
        read resp
        if [ $resp == "y" ]; then
            sudo rm -rf $dir
        else
            exit 0
        fi
    fi
    mkdir $dir
    _silent pushd $dir
    zcat ../$file | sudo cpio -i -H newc -d
    _silent popd
}

# remaster <core.gz> <initrd.gz>
function remaster() {
# Check arguments
    core=$1
    initrd=$2

    if [ -z $core ]; then
        echo "error: no 'core.gz' specified"
        return 1
    fi
    if [ -z $initrd ]; then
        echo "error: no 'initrd.gz' specified"
        return 1
    fi

    if ! [ -f $core ]; then
        echo "'"$core"' does not exist"
        return 1
    fi

# Unpack
    unpack $core initrd

# Introduce modifications 
    _silent pushd initrd

    # create mountpoint for iso
    sudo mkdir -p mnt/cdrom

    # WARNING: si pones una '/' delante
    # de todos los paths tipo 'cat > path' te cargas tu Linux!!

    # enable root terminal on serial port
    sudo sh -c "cat >> etc/inittab" <<EOF
# garzon
ttyS0::once:/bin/sh
EOF

    # permit execution of script from 'vda' partition
    sudo sh -c "cat >> opt/bootlocal.sh" <<EOF
# call init script in apps partition
source /mnt/vda/tce/bootlocal.sh 
EOF

    # create user 'garzon'
    sudo sh -c "cat >> etc/passwd" <<EOF
garzon:x:5000:5000:Garzon,,,:/home/garzon:/bin/sh
EOF
    sudo sh -c "cat >> etc/group" <<EOF
garzon:x:5000:
EOF
    sudo mkdir -p home/garzon
    sudo chown 5000:5000 home/garzon
    sudo chmod 700 home/garzon
   
# Repack
    sudo find | sudo cpio -o -H newc | gzip -2 > ../$initrd
    _silent popd
    sudo rm -rf initrd
}

# createimg <file.img>
function createimg() {
    file=$1
    sz=$2
    if [ -z $file ]; then
        echo "error: no file specified"
        exit 1
    fi
    if [ -z $sz ]; then
        echo "error: no size specified"
        exit 1
    fi
    if [ -f $file ]; then
        echo -n "File '"$file"' exists, overwrite (y/n)? "
        read resp
        if [ $resp == "y" ]; then
            rm -f $file
        else
            exit 0
        fi
    fi
    dd if=/dev/zero of=${file} bs=1M count=$sz
    sudo mkfs.ext3 -F ${file}
    _image_mount ${file}
    _image_init
    _image_umount
}

function pkglist() {
    cat <<EOF
gcc
go
EOF
}

function _install_gcc() {
    _download_packages gcc gcc_libs binutils gmp mpfr eglibc_base-dev libmpc 
    echo "eglibc_base-dev.tcz" | sudo sh -c "cat >> tce/optional/gcc.tcz.dep"
    _onboot gcc.tcz
}

function _install_go() {
    echo "Unimplemented"
    exit 1
}

function install() {
    _image_mount $1
    shift
    for pkg in $*; do
        case $pkg in
            gcc) _install_gcc ;;
            go)  _install_go ;;
        esac
    done
    _image_umount
}

function launch() {
    imgname=$1
    if ! [ -f $imgname ]; then
        echo "error: image '"$imgname"' doesn't exist"
        exit 1
    fi
    shift
    if ! [ -f vmlinuz ]; then
        echo "File 'vmlinuz' not found"
        exit 1
    fi
    if ! [ -f initrd.gz ]; then
        echo "File 'initrd.gz' not found"
        exit 1
    fi
    
    kvm -kernel vmlinuz -initrd initrd.gz \
        -append "tce=vda kmap=qwerty/es vga=788 nodhcp" \
        -drive "file=$imgname,if=virtio" \
        -net none \
        $*
}

function help() {    
    cat <<EOF
usage: grz-vm <command> [arguments]

command:
    download
    unpack <initrd.gz> <dir>
    remaster <core.gz> <initrd.gz>
    createimg <file.img>
    pkglist
    install <file.img> packages...
    launch <file.img> [-nographic]

EOF
}

if [ -z "$*" ]; then
    help
else
    $*
fi
